- hosts: k8s-masters[0]
  become: yes
  vars:
    upgrade_version: 1.23.9
  roles:
    - kubeadm-upgrade
    - kubeadm-apply
    - kubelet-upgrade

- hosts: k8s-masters[1:]
  serial: 1
  become: yes
  vars:
    upgrade_version: 1.23.9
  roles:
    - kubeadm-upgrade
    - kubeadm-node
    - kubelet-upgrade

- hosts: k8s-workers
  serial: 1
  become: yes
  vars:
    upgrade_version: 1.23.9
  roles:
    - kubeadm-upgrade
    - kubeadm-node
    - kubelet-upgrade